version: "3"
services:

  database:
    image: mysql:5.6
    restart: always
    container_name: proradis-test-rapha-mysql
    volumes:
      - proradis-test-rapha-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "3306:3306"
      
volumes:
  proradis-test-rapha-data: